### ISSUE TITLE
Update configuration

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-utilities-GoldScheduler#7]
Right now, the app is configured to use a MySQL database connection, but the configuration is outdated. Reconfigure the app to use a working MySQL DB connection.

**Comment by vivekpatel42** [comment]
F16 OK (100 pts)

**Comment by pconrad** [comment]
@milanes1 and @jamesy36 met with @ncbrown1 and worked on the MySQL stuff.    I also met with them today.    Between the four of us, we got this migrated over to sqlite3 with the build.xml and the jar files update.    Nick and I did most of the work, but James and Arturo should definitely get some credit for having brought the issue to us working through it with us.   

Check with me if there are any questions.  I want to be sure they don't get credit for work they didn't do, but at the same time, I also don't want them to get cheated out of points they have legitimately earned, and this is a case of a judgement call in between the two extremes of 0 points and all the points.
