### ISSUE TITLE
Email validation appears to only accept foo@bar.fum, but not foo@bar.fiddle.fum

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-utilities-GoldScheduler#9]
For example, foobar@umail.ucsb.edu would not be accepted.  Only foobar@gmail.com or foobar@ucsb.edu, but not foobar@cs.ucsb.edu

That sucks.  Fix it. 

F16 OK (100 pts)

**Comment by pconrad** [comment]
Check out this line of code:

https://github.com/jamesy36/cs56-utilities-GoldScheduler/blob/master/src/GUI/CreateAccount.java#L136

**Comment by pconrad** [comment]
Also see: https://docs.oracle.com/javase/tutorial/essential/regex/

http://www.ocpsoft.org/opensource/guide-to-regular-expressions-in-java-part-1/

and google "java regular expressions"

Also try "regular expression java validate email address" :-)

**Comment by Tektonbuilds** [comment]
They completed this issue so this should also touch base on the 500 points they needed for the first half of the project.
